var bgm_lovely_drive = {
    "rowLen": 5513,
    "endPattern": 29,
    "songData": [
        {
            "osc1_oct": 8,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 0,
            "osc1_waveform": 0,
            "osc2_oct": 8,
            "osc2_det": 0,
            "osc2_detune": 0,
            "osc2_xenv": 0,
            "osc2_vol": 0,
            "osc2_waveform": 0,
            "noise_fader": 255,
            "env_attack": 100000,
            "env_sustain": 100000,
            "env_release": 100000,
            "env_master": 92,
            "fx_filter": 2,
            "fx_freq": 2500,
            "fx_resonance": 16,
            "fx_delay_time": 2,
            "fx_delay_amt": 157,
            "fx_pan_freq": 1,
            "fx_pan_amt": 88,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 1,
            "lfo_freq": 2,
            "lfo_amt": 51,
            "lfo_waveform": 0,
            "p": [
                1,
                1,
                1,
                0,
                0,
                1,
                1,
                0,
                1,
                1,
                0,
                0,
                0,
                1,
                1,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                1
            ],
            "c": [
                {
                    "n": [
                        135,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 7,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 255,
            "osc1_waveform": 2,
            "osc2_oct": 8,
            "osc2_det": 0,
            "osc2_detune": 18,
            "osc2_xenv": 0,
            "osc2_vol": 255,
            "osc2_waveform": 2,
            "noise_fader": 0,
            "env_attack": 100000,
            "env_sustain": 56363,
            "env_release": 100000,
            "env_master": 75,
            "fx_filter": 2,
            "fx_freq": 200,
            "fx_resonance": 128,
            "fx_delay_time": 8,
            "fx_delay_amt": 24,
            "fx_pan_freq": 0,
            "fx_pan_amt": 0,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 0,
            "lfo_freq": 0,
            "lfo_amt": 0,
            "lfo_waveform": 0,
            "p": [
                0,
                1,
                2,
                1,
                2,
                1,
                2,
                0,
                0,
                0,
                1,
                2,
                1,
                1,
                0,
                0,
                0,
                1,
                2,
                0,
                0,
                1,
                2,
                0,
                0,
                1,
                2
            ],
            "c": [
                {
                    "n": [
                        128,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        147,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        128,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        123,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 7,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 192,
            "osc1_waveform": 0,
            "osc2_oct": 4,
            "osc2_det": 0,
            "osc2_detune": 0,
            "osc2_xenv": 0,
            "osc2_vol": 127,
            "osc2_waveform": 3,
            "noise_fader": 0,
            "env_attack": 100,
            "env_sustain": 150,
            "env_release": 13636,
            "env_master": 97,
            "fx_filter": 2,
            "fx_freq": 5839,
            "fx_resonance": 143,
            "fx_delay_time": 6,
            "fx_delay_amt": 52,
            "fx_pan_freq": 6,
            "fx_pan_amt": 147,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 1,
            "lfo_freq": 6,
            "lfo_amt": 195,
            "lfo_waveform": 0,
            "p": [
                0,
                0,
                0,
                1,
                2,
                1,
                0,
                0,
                0,
                2,
                1,
                2,
                0,
                0,
                0,
                0,
                2,
                1,
                2,
                1,
                2,
                1,
                2,
                1,
                2,
                1,
                2
            ],
            "c": [
                {
                    "n": [
                        168,
                        0,
                        0,
                        0,
                        0,
                        0,
                        171,
                        0,
                        0,
                        0,
                        0,
                        0,
                        173,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        168,
                        0,
                        0,
                        0,
                        0,
                        0,
                        171,
                        0,
                        0,
                        0,
                        0,
                        0,
                        168,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 8,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 0,
            "osc1_waveform": 0,
            "osc2_oct": 8,
            "osc2_det": 0,
            "osc2_detune": 0,
            "osc2_xenv": 0,
            "osc2_vol": 0,
            "osc2_waveform": 0,
            "noise_fader": 60,
            "env_attack": 50,
            "env_sustain": 419,
            "env_release": 4607,
            "env_master": 33,
            "fx_filter": 1,
            "fx_freq": 10332,
            "fx_resonance": 120,
            "fx_delay_time": 4,
            "fx_delay_amt": 16,
            "fx_pan_freq": 5,
            "fx_pan_amt": 108,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 0,
            "lfo_freq": 5,
            "lfo_amt": 187,
            "lfo_waveform": 0,
            "p": [
                0,
                0,
                1,
                1,
                1,
                2,
                2,
                2,
                1,
                0,
                1,
                2,
                1,
                1,
                2,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                2,
                1,
                1
            ],
            "c": [
                {
                    "n": [
                        171,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        171,
                        0,
                        171,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        171,
                        0,
                        0,
                        0,
                        0,
                        0,
                        171,
                        0
                    ]
                },
                {
                    "n": [
                        171,
                        0,
                        0,
                        0,
                        171,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        171,
                        0,
                        0,
                        0,
                        0,
                        171,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        171,
                        0,
                        0,
                        0,
                        171,
                        0,
                        0,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 6,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 1,
            "osc1_vol": 255,
            "osc1_waveform": 0,
            "osc2_oct": 6,
            "osc2_det": 0,
            "osc2_detune": 0,
            "osc2_xenv": 1,
            "osc2_vol": 255,
            "osc2_waveform": 0,
            "noise_fader": 8,
            "env_attack": 50,
            "env_sustain": 150,
            "env_release": 8181,
            "env_master": 97,
            "fx_filter": 2,
            "fx_freq": 5900,
            "fx_resonance": 240,
            "fx_delay_time": 6,
            "fx_delay_amt": 66,
            "fx_pan_freq": 0,
            "fx_pan_amt": 0,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 0,
            "lfo_freq": 0,
            "lfo_amt": 0,
            "lfo_waveform": 0,
            "p": [
                0,
                0,
                0,
                0,
                1,
                1,
                0,
                0,
                0,
                0,
                2,
                1,
                2,
                2,
                1,
                1,
                1,
                2,
                1,
                0,
                1,
                2,
                1,
                0,
                1,
                2,
                1
            ],
            "c": [
                {
                    "n": [
                        0,
                        0,
                        0,
                        0,
                        147,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        147,
                        0,
                        0,
                        150,
                        0,
                        0,
                        0,
                        0,
                        0,
                        135,
                        0,
                        151,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        0,
                        0,
                        0,
                        0,
                        147,
                        0,
                        0,
                        150,
                        0,
                        0,
                        0,
                        147,
                        0,
                        0,
                        150,
                        0,
                        0,
                        0,
                        0,
                        0,
                        135,
                        0,
                        151,
                        0,
                        0,
                        0,
                        0,
                        0,
                        135,
                        0,
                        151,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 7,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 192,
            "osc1_waveform": 0,
            "osc2_oct": 7,
            "osc2_det": 0,
            "osc2_detune": 0,
            "osc2_xenv": 0,
            "osc2_vol": 201,
            "osc2_waveform": 0,
            "noise_fader": 0,
            "env_attack": 100,
            "env_sustain": 150,
            "env_release": 13636,
            "env_master": 81,
            "fx_filter": 2,
            "fx_freq": 5839,
            "fx_resonance": 147,
            "fx_delay_time": 6,
            "fx_delay_amt": 108,
            "fx_pan_freq": 6,
            "fx_pan_amt": 147,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 1,
            "lfo_freq": 6,
            "lfo_amt": 195,
            "lfo_waveform": 0,
            "p": [
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                2,
                1,
                3,
                0,
                0,
                1,
                2,
                1,
                1,
                1,
                2,
                1,
                3,
                1,
                2,
                1,
                1,
                1,
                2,
                1,
                3
            ],
            "c": [
                {
                    "n": [
                        164,
                        0,
                        0,
                        0,
                        168,
                        0,
                        0,
                        0,
                        166,
                        0,
                        0,
                        0,
                        163,
                        0,
                        0,
                        0,
                        164,
                        0,
                        0,
                        0,
                        168,
                        0,
                        0,
                        0,
                        166,
                        0,
                        0,
                        0,
                        163,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        164,
                        0,
                        0,
                        0,
                        168,
                        0,
                        0,
                        0,
                        166,
                        0,
                        0,
                        0,
                        163,
                        0,
                        0,
                        0,
                        164,
                        0,
                        0,
                        0,
                        171,
                        0,
                        0,
                        0,
                        168,
                        0,
                        0,
                        0,
                        163,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        164,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ]
        }
    ],
    "songLen": 117
}
